### ISSUE TITLE
unpublish from npm

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-template#21]

**Comment by motin** [comment]
Closing since I clarified the deprecation message:
`npm deprecate -f 'shield-studies-addon-template@*' "Please clone this repository from https://github.com/mozilla/shield-studies-addon-template instead of installing via npm"`

Note: [There is no way to unpublish old packages from npm](https://www.npmjs.com/policies/unpublish) - only deprecation is possible.
